# Конфигурация RoadRunner для Laravel Octane.
version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php ./vendor/bin/roadrunner-worker"
  relay: pipes

http:
  address: "0.0.0.0:8080"
  middleware: ["static", "gzip"]
  static:
    dir: "public"
    forbid: [".php", ".htaccess"]
  pool:
    num_workers: 4
    supervisor:
      max_worker_memory: 256

logs:
  mode: production
  level: warn

metrics:
  address: "0.0.0.0:2112"
